# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_fimwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fimWindow(object):
    def setupUi(self, fimWindow):
        fimWindow.setObjectName("fimWindow")
        fimWindow.resize(537, 364)
        fimWindow.setMinimumSize(QtCore.QSize(536, 356))
        self.centralwidget = QtWidgets.QWidget(fimWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(520, 320))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.camView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.camView.sizePolicy().hasHeightForWidth())
        self.camView.setSizePolicy(sizePolicy)
        self.camView.setMinimumSize(QtCore.QSize(300, 300))
        self.camView.setSizeIncrement(QtCore.QSize(1, 1))
        self.camView.setAutoFillBackground(False)
        self.camView.setObjectName("camView")
        self.gridLayout_2.addWidget(self.camView, 1, 1, 1, 1)
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setObjectName("previewLabel")
        self.gridLayout_2.addWidget(self.previewLabel, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMeasurement = QtWidgets.QWidget()
        self.tabMeasurement.setObjectName("tabMeasurement")
        self.tabWidget.addTab(self.tabMeasurement, "")
        self.tabCam = QtWidgets.QWidget()
        self.tabCam.setObjectName("tabCam")
        self.tabWidget.addTab(self.tabCam, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 2, 1)
        fimWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fimWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecord = QtWidgets.QMenu(self.menubar)
        self.menuRecord.setObjectName("menuRecord")
        self.menuRefresh = QtWidgets.QMenu(self.menubar)
        self.menuRefresh.setObjectName("menuRefresh")
        self.menuSnapshot = QtWidgets.QMenu(self.menubar)
        self.menuSnapshot.setObjectName("menuSnapshot")
        fimWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(fimWindow)
        self.statusbar.setObjectName("statusbar")
        fimWindow.setStatusBar(self.statusbar)
        self.actionLoad_Parameters = QtWidgets.QAction(fimWindow)
        self.actionLoad_Parameters.setObjectName("actionLoad_Parameters")
        self.actionSave_Parameters = QtWidgets.QAction(fimWindow)
        self.actionSave_Parameters.setObjectName("actionSave_Parameters")
        self.menuFile.addAction(self.actionLoad_Parameters)
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRecord.menuAction())
        self.menubar.addAction(self.menuRefresh.menuAction())
        self.menubar.addAction(self.menuSnapshot.menuAction())

        self.retranslateUi(fimWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(fimWindow)

    def retranslateUi(self, fimWindow):
        _translate = QtCore.QCoreApplication.translate
        fimWindow.setWindowTitle(_translate("fimWindow", "FIMrecorder"))
        self.previewLabel.setText(_translate("fimWindow", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMeasurement), _translate("fimWindow", "Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCam), _translate("fimWindow", "Camera"))
        self.menuFile.setTitle(_translate("fimWindow", "File"))
        self.menuRecord.setTitle(_translate("fimWindow", "Record"))
        self.menuRefresh.setTitle(_translate("fimWindow", "Refresh"))
        self.menuSnapshot.setTitle(_translate("fimWindow", "Snapshot"))
        self.actionLoad_Parameters.setText(_translate("fimWindow", "Load Parameters"))
        self.actionSave_Parameters.setText(_translate("fimWindow", "Save Parameters"))

